apiVersion: v1
kind: ServiceAccount
metadata:
  name: shell-demo
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: shell-demo-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create

---
# kubectl create rolebinding shell-demo-rb --role=shell-demo-role --user=shell-demo --namespace=default
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: shell-demo-rb
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shell-demo-role
subjects:
- kind: ServiceAccount
  name: shell-demo
---

apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  serviceAccountName: shell-demo
  hostNetwork: true
  dnsPolicy: Default